substitutions:
  project_ver_let: u
  default_power_on_state: "Always On - Bright White"
  wifi_ap_timeout: 15s    # default to 15 second timeout for update bin file


packages:
  kauf_bulb_base:
    url: https://github.com/KaufHA/kauf-rgbww-bulbs
    files: kauf-bulb.yaml
    refresh: 0s


dashboard_import:
  package_import_url: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb.yaml


esphome:
  name_add_mac_suffix: true


# add new button to clear wifi credentials.  Not needed in dashboard import
# version as credentials are hard coded
button:
  - platform: template
    id: clear_wifi_button
    name: $friendly_name Clear Wifi Credentials
    entity_category: diagnostic
    disabled_by_default: true
    on_press:
      then:
      - lambda: 'wifi_wificomponent->clear_stored_creds();'
      - delay: 2s
      - button.press: restart_button


wifi:

  # by default, fast_connect is disabled.  Will automatically be enabled by wifi component
  # needs to be set false here as dashboard import version sets true
  fast_connect: false

  # add forced hash which isn't needed for dashboard import.  Allows saving wifi credentials across update.
  forced_hash: 2048874009
