# https://esphome.io/guides/configuration-types.html#substitutions
substitutions:

  # substitutions can be changed here if you are using this file directly in the ESPHome dashboard.  The better approach is
  # to incorporate this file as a package using the following lines, and then overwrite these substitutions in your local
  # yaml file by redefining them.
  #
  # packages:
  #   kauf.rgbww: github://KaufHA/kauf-rgbww-bulbs/kauf-bulb-lite.yaml
  #

  name: kauf-bulb              # **** CHANGE DEVICE NAME TO SOMETHING UNIQUE PER DEVICE.  RENAME YAML FILE TO SAME NAME.    ****
                               # **** USE DASHES (-) INSTEAD OF SPACES OR UNDERSCORE (_).  USE ONLY LOWER CASE LETTERS.     ****

  friendly_name: Kauf Bulb     # **** CHANGE FRIENDLY NAME TO SOMETHING UNIQUE PER DEVICE ****

  disable_entities: "true"     # set to "false" to have all entities show up in Home Assistant automatically

  # https://esphome.io/components/light/index.html#base-light-configuration
  light_restore_mode: RESTORE_INVERTED_DEFAULT_OFF  # change power-on action for main light entity
  default_power_on_state: "Restore Power Off State"

  wifi_ap_timeout: 2min    # default to 2 minute timeout for yaml file as package.

  # https://esphome.io/components/esphome.html#esphome-creators-project
  project_name: Kauf.RGBWW
  project_ver_num: "1.85"
  project_ver_let: l

  sub_on_turn_on:  script_do_nothing
  sub_on_turn_off: script_do_nothing


# https://esphome.io/components/esp8266.html
esp8266:
  board: esp01_1m
  restore_from_flash: true


# https://esphome.io/components/esphome.html
esphome:

  name: $name

  project:
    name: $project_name
    version: $project_ver_num($project_ver_let)


# https://esphome.io/components/button/index.html
# https://esphome.io/components/button/restart.html
button:
  - platform: restart
    id: restart_button
    name: $friendly_name Restart Firmware
    entity_category: diagnostic
    disabled_by_default: $disable_entities


# https://esphome.io/components/wifi.html
wifi:

  ssid: initial_ap
  password: asdfasdfasdfasdf

  # default is 20, 17 is recommended.
  output_power: 17

  # using fast_connect as default since it is required for hidden networks.
  fast_connect: true

  ap:
    ap_timeout: $wifi_ap_timeout


# https://esphome.io/components/captive_portal.html
captive_portal:


# https://esphome.io/components/logger.html
logger:


# https://esphome.io/components/api.html
api:
  id: kauf_api


# https://esphome.io/components/ota.html
ota:
  on_error:
    then:
      - button.press: restart_button


# https://esphome.io/components/web_server.html
web_server:
  local: true


# PWM outputs for each LED channel
# https://esphome.io/components/output/esp8266_pwm.html
output:
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_red
    max_power: .85
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_green
    max_power: .85
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_blue
    max_power: .85
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 1000 Hz
    id: pwm_cw
    max_power: .85
  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm_ww
    max_power: .85


# https://esphome.io/components/light/index.html
light:
  - platform: rgbww
    name: $friendly_name
    id: kauf_light
    red: pwm_red
    green: pwm_green
    blue: pwm_blue
    warm_white: pwm_ww
    cold_white: pwm_cw
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K


# https://esphome.io/components/select/index.html
# https://esphome.io/components/select/template.html
select:

  # default light state on boot
  - platform: template
    name: $friendly_name Power On State
    id: select_boot_state
    optimistic: true
    options:
      - "Restore Power Off State"
      - "Always On - Last Value"
      - "Always On - Bright White"
      - "Always Off"
      - "YAML Configured ($light_restore_mode)"
    # defaulting to always on is nice so you know new bulbs are working
    initial_option: $default_power_on_state
    restore_value: true
    icon: mdi:restart-alert
    on_value:
      - lambda: |-
          if ( x == "Restore Power Off State")
            kauf_light->set_restore_mode(LIGHT_RESTORE_DEFAULT_OFF);
          else if ( x == "Always On - Last Value")
            kauf_light->set_restore_mode(LIGHT_RESTORE_AND_ON);
          else if ( x == "Always On - Bright White")
            kauf_light->set_restore_mode(LIGHT_ALWAYS_ON);
          else if ( x == "Always Off")
            kauf_light->set_restore_mode(LIGHT_RESTORE_AND_OFF);
          else
            kauf_light->set_restore_mode(LIGHT_$light_restore_mode);
          kauf_light->save_remote_values_();
      - script.execute: script_save_changes
    entity_category: config


# https://esphome.io/components/number/index.html
# https://esphome.io/components/number/template.html
number:      # set max power output for PWMs
  - platform: template
    name: ${friendly_name} Max Power
    min_value: 1
    max_value: 100
    step: 1
    initial_value: 85
    id: number_max_power
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:brightness-percent
    optimistic: true
    restore_value: true
    unit_of_measurement: "%"
    mode: box
    on_value:
      - lambda: |-
          float new_power = ((float)x)/100.0f;
          id(pwm_red).set_max_power(new_power);
          id(pwm_green).set_max_power(new_power);
          id(pwm_blue).set_max_power(new_power);
          id(pwm_ww).set_max_power(new_power);
          id(pwm_cw).set_max_power(new_power);
          id(kauf_light)->set_next_write();
      - script.execute: script_save_changes

  - platform: template
    name: ${friendly_name} Default Fade
    min_value: 0
    max_value: 5000
    step: 50
    initial_value: 250
    id: number_default_fade
    entity_category: config
    icon: mdi:timer-outline
    optimistic: true
    restore_value: true
    unit_of_measurement: "ms"
    mode: box
    on_value:
      - lambda: id(kauf_light)->set_default_transition_length(x);
      - script.execute: script_save_changes


# https://esphome.io/components/switch/index.html
# https://esphome.io/components/switch/template.html
switch:
  - platform: template
    id: switch_no_hass
    name: $friendly_name No HASS
    optimistic: true
    restore_state: true
    entity_category: config
    disabled_by_default: $disable_entities
    icon: mdi:toggle-switch-off-outline
    on_turn_on:
      - lambda: id(kauf_api)->set_reboot_timeout(0);
      - script.execute: script_save_changes
    on_turn_off:
      - lambda: id(kauf_api)->set_reboot_timeout(900000);
      - script.execute: script_save_changes


# https://esphome.io/components/sensor/uptime.html
sensor:
  - platform: uptime
    name: $friendly_name Uptime
    update_interval: 60s
    entity_category: diagnostic
    disabled_by_default: $disable_entities


# Send IP Address to HA.
# https://esphome.io/components/text_sensor/wifi_info.html
text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address
      entity_category: diagnostic
      disabled_by_default: $disable_entities


# https://esphome.io/guides/automations.html#script-component
script:
  - id: script_save_changes
    mode: restart
    then:
      - delay: 3s
      - lambda: global_preferences->sync();

  - id: script_do_nothing
    then:
      lambda: return;
