packages:
  kauf_bulb_update:
    url: https://github.com/KaufHA/kauf-rgbww-bulbs
    files: config-update/kauf-bulb-update.yaml
    refresh: 0s


esphome:

  project:
    name: "kauf.rgbww"
    version: "1.73f"        # f = factory

  on_boot:
    then:

      - if:
          condition:
            lambda: |-
              return id(first_boot);
          then:
            - while:               # repeat test pattern 30 times total to get to 10 minutes
                condition:
                  lambda: |-
                    return (id(test_count) < 30);   
                then:

                  - logger.log:
                      format: "[5] Test Pattern Starting"
                      tag: "KAUF Test"

                  - light.turn_on:
                      id: kauf_light
                      brightness: 100%
                      color_temperature: 350 mireds
                      transition_length: 2s
                  - delay: 4s

                  - logger.log:
                      format: "[4] Test Pattern to Warm"
                      tag: "KAUF Test"

                  - light.turn_on:
                      id: kauf_light
                      brightness: 100%
                      color_temperature: 150 mireds
                      transition_length: 2s
                  - delay: 4s

                  - logger.log:
                      format: "[3] Test Pattern to Red"
                      tag: "KAUF Test"

                    # light on to red
                  - light.turn_on:
                      id: kauf_light
                      brightness: 100%
                      red: 100%
                      blue: 0%
                      green: 0%
                      transition_length: 2s
                  - delay: 4s

                  - logger.log:
                      format: "[2] Test Pattern to Green"
                      tag: "KAUF Test"

                  # light on to green
                  - light.turn_on:
                      id: kauf_light
                      brightness: 100%
                      red: 0%
                      blue: 0%
                      green: 100%
                      transition_length: 2s
                  - delay: 4s

                  - logger.log:
                      format: "[1] Test Pattern to Blue"
                      tag: "KAUF Test"
      
                  # light on to blue
                  - light.turn_on:
                      id: kauf_light
                      brightness: 100%
                      red: 0%
                      blue: 100%
                      green: 0%
                      transition_length: 2s
                  - delay: 4s

                  - lambda: |-
                      id(test_count) += 1;
                      ESP_LOGD("KAUF Test", "[0] Test Pattern Completed %d/30", id(test_count) );

      # after test pattern completes or if it already completed:
      - globals.set:
          id: first_boot
          value: 'false'

      # return to white light
      - light.turn_on:
          id: kauf_light
          brightness: 100%
          color_temperature: 150 mireds


globals:

  # used to run routine at factory to confirm 
  # firmware is running.
  - id: first_boot
    type: bool
    restore_value: yes
    initial_value: 'true'
  - id: test_count
    type: int
    restore_value: no
    initial_value: '0'
